services:

# Connection string: docker exec -it postgresdb psql -U migrator -d music_database
# To generate the pgdump.sql file: docker compose exec -T postgres pg_dump -U postgres music_database > pgdump.sql
  postgres:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music_database
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# No Default User: By default, MongoDB does not come with any user accounts or authentication enabled. 
# Start MongoDB without enabling authentication, anyone can connect to the database without a username or password.

# Mongodbdump gen: docker exec -it mongodb mongodump --db your_database_name --out /data/db/dump

# Connection string: docker exec -it mongodb mongosh
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: