version: "3.7"
services:
  node-api-file-upload:
    restart: always

    build:
      context: ./01._Node
      target: develop
      dockerfile: Dockerfile.dev

    volumes:
      - ./01._Node:/app

    ports:
      - 8080:8080

  python-api-file-upload:
    build:
      context: ./02._Python
      target: develop
      dockerfile: Dockerfile.dev

    volumes:
      - ./02._Python:/app

    ports:
      - 8000:8000