# docker build -f Dockerfile.prod -t webhook-app .
# docker run -p 8080:8080 webhook-app
FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:16-alpine AS production

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=build /app/dist ./dist
COPY --from=build /app/assets ./assets

CMD ["node", "dist/app.js"]
