services:
  webhook-app:
    image: ghcr.io/realkoder/sys-int-webhook-app:latest
    pull_policy: always
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app/assets
    environment:
      - NODE_ENV=production