services:
  webhook-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app/assets
    environment:
      - NODE_ENV=production